# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: S-Ential Technologies
email: support@s-entialtechnologies.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to S-Ential Technologies. Our company is focussed on providing
  IT solutions to small and meduim sized businesses across the East African region.
  S-Ential Technologies offers SaaS as well as customized softwares that help businesses
  leverage potential by increasing revenues, efficiency, speed and security. Our website url is https://www.s-entialtechnologies.com.
  Our products are powered by Amazon Web Services (AWS).
   
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.s-entialtechnologies.com" # the base hostname & protocol for your site, e.g. http://example.com

host: 0.0.0.0

#permalink: "category/:categories/:year/:month/:day/:title/"
twitter_username: kobare
github_username:  kobare
discus_identifier: admin11
mailchimp: github.us8.list-manage.com/subscribe/post?u=59f41437739e3691e8b775c88&amp;id=6ac77103af


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
